# Generated by Django 3.0.8 on 2022-04-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220314_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
