# Generated by Django 3.0.8 on 2022-04-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_groupchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
